# options for analysis running
run:
  # include test files or not, default is true
  tests: false

linters-settings:
  golint:
    # minimal confidence for issues, default is 0.8
    min-confidence: 0.8

exclude-rules:
  # Exclude some linters from running on tests files.
  - path: _test\.go
    linters:
      - errcheck