name: Integration

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**/*.rst'
      - '**/*.md'
    branches:
      - master
      - main
      - '[0-9].[0-9]'
    pull_request:
      branches:
        - master
        - main
        - '[0-9].[0-9]'
    schedule:
      - cron: '0 1 * * *'

jobs:

  lint:
    name: Code linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          make checkfmt
          make lint

  integration:
    services:
      image: redis/redis-stack-server:latest
      port:
        - 6379:6379
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - uses: actions/checkout@v3
      - run: |
          make get
          make coverage
      - name: Upload coverage
        uses: codecov/codecov-action@v3
